<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.epam.tat.unittest.CalculatorTest" tests="9" time="0.020" ignored="0" failures="1" timestamp="06 Mar 2017 13:26:50 GMT" skipped="0" hostname="EPBYMINW3743" errors="0">
  <testcase name="testSumMethos" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testSumMethos" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testSumMethos" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testMultMethod" time="0.000" classname="com.epam.tat.unittest.CalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of the operation, correct result: 0.0 expected [0.0] but found [-0.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of the operation, correct result: 0.0 expected [0.0] but found [-0.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at com.epam.tat.unittest.CalculatorTest.testMultMethod(CalculatorTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testMultMethod -->
  <testcase name="testMultMethod" time="0.010" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testMultMethod" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testMultMethod" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testSumMethos" time="0.000" classname="com.epam.tat.unittest.CalculatorTest"/>
  <testcase name="testMultMethod" time="0.010" classname="com.epam.tat.unittest.CalculatorTest"/>
</testsuite> <!-- com.epam.tat.unittest.CalculatorTest -->
